name: Android CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - uses: actions/checkout@v4.2.2

    - name: set up JDK 17
      uses: actions/setup-java@v4.7.0
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4.0.0
      with:
        gradle-version: '8.7' # Kita paksa install Gradle 8.7 secara global

    - name: Build with Gradle
      run: |
        # Cari di mana folder 'app' berada
        APP_PATH=$(find . -name "build.gradle" -exec grep -l "com.android.application" {} \;)
        PROJECT_ROOT=$(dirname $(dirname "$APP_PATH"))
        
        echo "Project detected at: $PROJECT_ROOT"
        cd "$PROJECT_ROOT"
        
        # Gunakan 'gradle' sistem, bukan './gradlew' lokal
        gradle assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4.6.0
      with:
        name: CamRU-Professional-APK
        path: "**/build/outputs/apk/debug/*.apk"
